### ISSUE TITLE
ViewModelFactory should be in app module, not in base

### ISSUE THREAD

**Issue by jonyas** [anstaendig/ArchitectureComponents#20]

**Comment by jonyas** [comment]
opened for discussion, since I am not sure. Too DI related, what do you think @anstaendig

**Comment by anstaendig** [comment]
I was thinking about using a structure similar to [this](https://github.com/bufferapp/clean-architecture-components-boilerplate). In that case the `ViewModelFactory` would be part of the presentation layer without knowing about the ui which I really like.

**Comment by anstaendig** [comment]
#24 will take care of it.
